version: '3.4'

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  nestify:
    image: davesagraf/nestify:nestify_back
    container_name: nestify
    env_file:
      - .env
    build: 
      context: https://github.com/davesagraf/nestify.git
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - postgres  

  nestify-frontend:
    image: davesagraf/nestify:nestify_front
    container_name: nestify-frontend
    build:
      context: https://github.com/davesagraf/nestify-frontend.git
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    links:
      - nestify     