import { IUser, UserRole } from 'src/entity/interface/userEntity.interface';

export const users: IUser[] = [
  {
    id: 1,
    role: UserRole.REGULAR,
    email: 'aaa@dev.com',
    password: 'aaadev1',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 2,
    role: UserRole.REGULAR,
    email: 'bbb@dev.com',
    password: 'bbbdev2',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 3,
    role: UserRole.REGULAR,
    email: 'ccc@dev.com',
    password: 'cccdev3',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 4,
    role: UserRole.REGULAR,
    email: 'ddd@dev.com',
    password: 'ddddev4',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 5,
    role: UserRole.REGULAR,
    email: 'aaaaaaa@dev.com',
    password: 'aaaaaaadev5',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 6,
    role: UserRole.REGULAR,
    email: 'bbbbbbb@dev.com',
    password: 'bbbbbbbdev6',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 7,
    role: UserRole.REGULAR,
    email: 'xxx@dev.com',
    password: 'xxxdev7',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 8,
    role: UserRole.REGULAR,
    email: 'zzz@dev.com',
    password: 'zzzdev8',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 9,
    role: UserRole.REGULAR,
    email: 'yyy@dev.com',
    password: 'yyydev9',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 10,
    role: UserRole.REGULAR,
    email: 'vvv@dev.com',
    password: 'vvvdev10',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 11,
    role: UserRole.REGULAR,
    email: 'vvvvvvvvv@dev.com',
    password: 'vvvvvvvvvdev11',
    firstName: 'dave',
    lastName: 'dev',
    isActive: true,
    lectures: [],
  },
  {
    id: 12,
    role: UserRole.REGULAR,
    email: 'rrr@dev.com',
    password: 'rrrdev12',
    firstName: 'mark',
    lastName: 'mmm',
    isActive: true,
    lectures: [],
  },
  {
    id: 13,
    role: UserRole.ADMIN,
    email: 'fucking@dumbass.com',
    password: 'fuckingdumbass13',
    firstName: 'Fucking',
    lastName: 'Dumbass',
    isActive: true,
    lectures: [],
  },
];
